# Generated by Django 6.0.2 on 2026-03-02 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskName',
            new_name='task',
        ),
    ]
