# Generated by Django 6.0.2 on 2026-03-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_taskname_task_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isAchieved',
            field=models.BinaryField(default=False),
        ),
    ]
