# Generated by Django 6.0.2 on 2026-03-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_isachieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='isAchieved',
            field=models.BooleanField(default=False),
        ),
    ]
